# Generated by Django 5.0.2 on 2024-03-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
    ]
