# Generated by Django 5.0.2 on 2024-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
