# Generated by Django 5.0.2 on 2024-03-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_statusupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
    ]
