# Generated by Django 5.0.2 on 2024-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_user_type_alter_customuser_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/admin/img/avatar.svg",
                null=True,
                upload_to="static/admin/img/",
                verbose_name="Avatar",
            ),
        ),
    ]
