# Generated by Django 5.0.3 on 2024-03-06 09:28

from django.db import migrations

def create_default_chatroom(apps, schema_editor):
    ChatRoom = apps.get_model('main', 'ChatRoom')
    ChatRoom.objects.get_or_create(title='Public Room')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_chatroom),
    ]
