# Generated by Django 5.0.2 on 2024-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_chatroom_members_alter_chatroom_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
